Improve help message output, Maven executable probing

diff --git a/.local/bin/maven_verify_multi_module b/.local/bin/maven_verify_multi_module
--- a/.local/bin/maven_verify_multi_module
+++ b/.local/bin/maven_verify_multi_module
@@ -9,8 +9,6 @@
 #
 # https://twitter.com/gunnarmorling/status/1463792047316520965
 
-# TODO: check if `./mvnw` is available, then if `mvn` is available, bail out if nothing is available
-
 # ARG_OPTIONAL_SINGLE([compile-or-install],[c],[Whether to compile only or install the dependencies.])
 # ARG_OPTIONAL_BOOLEAN([dependencies-skip-tests],[s],[Whether to skip tests on dependencies install phase or not.])
 # ARG_POSITIONAL_SINGLE([target-module],[The target module for which the tests should be run for.],[])
@@ -22,21 +20,23 @@
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 # Generated online by https://argbash.io/generate
 
+_fmt_bold=$(tput bold)
+_fmt_red=$(tput setaf 1)
+_fmt_blue=$(tput setaf 4)
+_fmt_normal=$(tput sgr0)
 
-die()
-{
-	local _ret="${2:-1}"
-	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
-	exit "${_ret}"
+die() {
+  local _ret="${2:-1}"
+  test "${_PRINT_HELP:-no}" = yes && print_help >&2
+  echo "$1" >&2
+  exit "${_ret}"
 }
 
 
-begins_with_short_option()
-{
-	local first_option all_short_options='csh'
-	first_option="${1:0:1}"
-	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+begins_with_short_option() {
+  local first_option all_short_options='csh'
+  first_option="${1:0:1}"
+  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
@@ -46,87 +46,134 @@ _arg_compile_or_install="compile"
 _arg_dependencies_skip_tests="false"
 
 
-print_help()
-{
-	printf '%s\n' "Run a lightweight verify goal on a (complex) Maven multi-module project."
-	printf '%s\n' ""
-	printf 'Usage: %s [-c|--compile-or-install <arg>] [-s|--(no-)dependencies-skip-tests] [-h|--help] <target-module(s)>\n' "$0"
-	printf '\t%s\n' "<target-module(s)>: The target module(s) for which the tests should be run for. Comma separated if multiple modules should be targeted, e.g. 'mod1,mod2'."
-	printf '\t%s\n' "-c, --compile-or-install: Whether to 'compile' only or 'install' the dependencies. (defaults to 'compile')"
-	printf '\t%s\n' "-s, --dependencies-skip-tests, --no-dependencies-skip-tests: Whether to skip tests on dependencies build phase or not. ('false' by default)"
-	printf '\t%s\n' "-h, --help: Prints help"
+print_help() {
+  printf '%s\n' "${_fmt_bold}NAME${_fmt_normal}"
+  printf '\t%s - %s\n' "${_fmt_bold}MVVM${_fmt_normal}" "Focused test execution of specific modules in a Maven multi-module project."
+  printf '%s\n' ""
+  printf '%s\n' "${_fmt_bold}SYNOPSIS${_fmt_normal}"
+  printf '\t%s [-c|--compile-or-install <arg>]\n' $(basename "$0")
+  printf '%33s [-s|--(no-)dependencies-skip-tests]\n' ''
+  printf '%33s [-h|--help] <target-module(s)>\n' ''
+  printf '%s\n' ""
+  printf '%s\n' "${_fmt_bold}DESCRIPTION${_fmt_normal}"
+  printf '\t%s\n' "Running tests on a (complex) Maven multi-module project for a specifc"
+  printf '\t%s\n' "target module can be time consuming. This script helps to 'compile' or"
+  printf '\t%s\n' "'install' the dependencies for that target module and runs the test of"
+  printf '\t%s\n' "that target module afterwards."
+  printf '%s\n' ""
+  printf '\t%s\n' "This helper requires either a locally available Maven wrapper (mvnw) or"
+  printf '\t%s\n' "a globally installed Maven binary."
+  printf '%s\n' ""
+  printf '%s\n' "${_fmt_bold}OPTIONS${_fmt_normal}"
+  printf '\t%s\n' "-c, --compile-or-install"
+  printf '\t\t%s\n' "Whether to 'compile' only or 'install' the dependencies."
+  printf '\t\t%s\n' "(defaults to 'compile')"
+  printf '%s\n' ""
+  printf '\t%s\n' "-s, --dependencies-skip-tests, --no-dependencies-skip-tests"
+  printf '\t\t%s\n' "Whether to skip tests on dependencies build phase or not."
+  printf '\t\t%s\n' "(defaults to 'false')"
+  printf '%s\n' ""
+  printf '\t%s\n' "-h, --help"
+  printf '\t\t%s\n' "Prints help"
+  printf '%s\n' ""
+  printf '\t%s\n' "<target-module(s)>"
+  printf '\t\t%s\n' "The target module(s) for which the tests should be run for."
+  printf '\t\t%s\n' "Comma-separated if multiple modules should be targeted."
+  printf '%s\n' ""
+  printf '%s\n' "${_fmt_bold}EXAMPLES${_fmt_normal}"
+  printf '\t%s\n' "If the multi module project you're working on makes it necessary to"
+  printf '\t%s\n' "install the dependencies, use the '-c|--compile-or-install' argument"
+  printf '\t%s\n' "with the value set to 'install':"
+  printf '%s\n' ""
+  printf '\t\t$ %s %s\n' $(basename "$0") "-c install <target-module>"
+  printf '%s\n' ""
+  printf '\t%s\n' "If you don't want to run the tests of the dependencies of the target"
+  printf '\t%s\n' "module, use the '-s|--(no-)dependencies-skip-tests' flag:"
+  printf '%s\n' ""
+  printf '\t\t$ %s %s\n' $(basename "$0") "-s <target-module>"
+  printf '%s\n' ""
+  printf '\t%s\n' "If you don't want to run the helper for multiple target modules, use"
+  printf '\t%s\n' "a comma-separated list of module names:"
+  printf '%s\n' ""
+  printf '\t\t$ %s %s\n' $(basename "$0") "mod1,mod2"
+  printf '%s\n' ""
+  printf '%s\n' "${_fmt_bold}AUTHOR${_fmt_normal}"
+  printf '\t\t%s\n' "Thomas Juhnke <contact@dreadlabs.de>"
+  printf '%s\n' ""
+  printf '%s\n' "${_fmt_bold}COPYRIGHT${_fmt_normal}"
+  printf '\t\t%s\n' "(c) 2021, License: MIT"
+  printf '%s\n' ""
+  printf '%s\n' "${_fmt_bold}EOH${_fmt_normal}"
+  printf '%s\n' ""
 }
 
 
-parse_commandline()
-{
-	_positionals_count=0
-	while test $# -gt 0
-	do
-		_key="$1"
-		case "$_key" in
-			-c|--compile-or-install)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_compile_or_install="$2"
-				shift
-				;;
-			--compile-or-install=*)
-				_arg_compile_or_install="${_key##--compile-or-install=}"
-				;;
-			-c*)
-				_arg_compile_or_install="${_key##-c}"
-				;;
-			-s|--no-dependencies-skip-tests|--dependencies-skip-tests)
-				_arg_dependencies_skip_tests="true"
-				test "${1:0:5}" = "--no-" && _arg_dependencies_skip_tests="false"
-				;;
-			-s*)
-				_arg_dependencies_skip_tests="true"
-				_next="${_key##-s}"
-				if test -n "$_next" -a "$_next" != "$_key"
-				then
-					{ begins_with_short_option "$_next" && shift && set -- "-s" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-				fi
-				;;
-			-h|--help)
-				print_help
-				exit 0
-				;;
-			-h*)
-				print_help
-				exit 0
-				;;
-			*)
-				_last_positional="$1"
-				_positionals+=("$_last_positional")
-				_positionals_count=$((_positionals_count + 1))
-				;;
-		esac
-		shift
-	done
+parse_commandline() {
+  _positionals_count=0
+  while test $# -gt 0
+  do
+    _key="$1"
+    case "$_key" in
+      -c|--compile-or-install)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_compile_or_install="$2"
+        shift
+        ;;
+      --compile-or-install=*)
+        _arg_compile_or_install="${_key##--compile-or-install=}"
+        ;;
+      -c*)
+        _arg_compile_or_install="${_key##-c}"
+        ;;
+      -s|--no-dependencies-skip-tests|--dependencies-skip-tests)
+        _arg_dependencies_skip_tests="true"
+        test "${1:0:5}" = "--no-" && _arg_dependencies_skip_tests="false"
+        ;;
+      -s*)
+        _arg_dependencies_skip_tests="true"
+        _next="${_key##-s}"
+        if test -n "$_next" -a "$_next" != "$_key"
+        then
+          { begins_with_short_option "$_next" && shift && set -- "-s" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
+        ;;
+      -h|--help)
+        print_help
+        exit 0
+        ;;
+      -h*)
+        print_help
+        exit 0
+        ;;
+      *)
+        _last_positional="$1"
+        _positionals+=("$_last_positional")
+        _positionals_count=$((_positionals_count + 1))
+        ;;
+    esac
+    shift
+  done
 }
 
 
-handle_passed_args_count()
-{
-	local _required_args_string="'target-module'"
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+handle_passed_args_count() {
+  local _required_args_string="'target-module'"
+  test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+  test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
 
-assign_positional_args()
-{
-	local _positional_name _shift_for=$1
-	_positional_names="_arg_target_module "
+assign_positional_args() {
+  local _positional_name _shift_for=$1
+  _positional_names="_arg_target_module "
 
-	shift "$_shift_for"
-	for _positional_name in ${_positional_names}
-	do
-		test $# -gt 0 || break
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
-		shift
-	done
+  shift "$_shift_for"
+  for _positional_name in ${_positional_names}
+  do
+    test $# -gt 0 || break
+    eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+    shift
+  done
 }
 
 parse_commandline "$@"
@@ -138,6 +185,23 @@ assign_positional_args 1 "${_positionals[@]}"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
-./mvnw clean $_arg_compile_or_install -DskipTests=$_arg_dependencies_skip_tests -pl :"$_arg_target_module" -am && ./mvnw clean verify -pl :"$_arg_target_module"
+# TODO: check if `./mvnw` is available, then if `mvn` is available, bail out if nothing is available
+
+_maven_command_global="mvn"
+_maven_command_wrapper="./mvnw"
+_maven_command=""
+
+if type "$_maven_command_wrapper" &> /dev/null; then
+  printf '%s\n' "[${_fmt_blue}INFO${_fmt_normal}] MVMM: Using local Maven wrapper."
+  _maven_command="$_maven_command_wrapper"
+elif type "$_maven_command_global" &> /dev/null; then
+  printf '%s\n' "[${_fmt_blue}INFO${_fmt_normal}] MVMM: Using global Maven binary."
+  _maven_command="$_maven_command_global"
+else
+  _PRINT_HELP=no die "[${_fmt_red}ERROR${_fmt_normal}] No Maven executable found." 1
+fi
+
+$_maven_command clean $_arg_compile_or_install -DskipTests=$_arg_dependencies_skip_tests -pl :"$_arg_target_module" -am && \
+$_maven_command clean verify -pl :"$_arg_target_module"
 
 # ] <-- needed because of Argbash
